### PR TITLE
Create docs-zh-CN.md

### PR DESCRIPTION
**Pull request by yisharp**
a little zh-CN for "about docs" , translation and format is not done, maybe there are mistakes, hope others can continue. 
(it's my first translation and pr)

### CODE REVIEW

**Comment by sh-dv** [comment]
Hello, this issue is reopened because it is something in development now in the [hat.sh Dev branch](https://github.com/sh-dv/hat.sh/tree/dev/).
You are more than welcomed to translate to Chinese language, i made it easy for you, all you have to do is edit the 2 files in the [`locales/cn` directory](https://github.com/sh-dv/hat.sh/tree/dev/locales/cn). 

Also if you want to test it out, you can clone the Dev branch then `npm i && npm run dev`. 
You can also read the translation [guide](https://github.com/sh-dv/hat.sh/tree/dev/locales#readme), although there is no need because i already created the files for you.

Make sure you pull request the Dev branch.
Your github account will be credited after the main branch merge.

Regards, 
sh-dv

**Comment by sh-dv** [comment]
This will be closed if there is no response in 7 more days.

**Comment by yisharp** [comment]
sorry I am busy now ...

**Comment by sh-dv** [comment]
np

**Pull request closed without merging**
