### PR TITLE
Improve translation setup

### PR DESCRIPTION
**Pull request by stophecom**
This PR further improves localization (translation) of the app. 

## PR in a nutshell
- [Internationalized routing](https://nextjs.org/docs/advanced-features/i18n-routing). Make use of the built-in next internationalization concepts. Translated versions have separate routes now: e.g. for French: `hat.sh/fr/`
- Language will be chosen based on browser settings 
- If language is switched manually, it will be stored in cookie (Used this instead of local storage since it's a [built-in-feature](https://nextjs.org/docs/advanced-features/i18n-routing#leveraging-the-next_locale-cookie))
- Add proper `hreflang` meta tags to tell Google about localized versions of the page. [More info](https://developers.google.com/search/docs/advanced/crawling/localized-versions)
- Added `next-i18next` that uses [i18next](https://www.i18next.com/) under the hood. It comes with `useTranslation` (and  `t` function). It will make further translations much easier, b/c it has _interpolation_, _plurals_, etc. 

## Changes summarized
- I moved translation files based on `next-i18next` recommended setup (This means the files are proper `.json` now)
- There is new config `next-i18next.config.js` 
- All pages need to export `getStaticProps` 
  ``` 
   return {
      props: {
        ...(await serverSideTranslations(locale, ["common"])),
      },
  ```
- I changed language codes. Imo the language `en` code (opposed to `en-US`) is in sufficient. I mean if I come from UK I'd rather get `hat.sh/en` instead of `hat.sh/en-US` (I'm also not 100% sure how the language is negotiated in the end.)
- I might have changed some unrelated code due to my formatter. Problem is that formatting was inconsistent, e.g. double vs. single quotes. Sorry about that. Maybe you could add prettier config (or other solution) to help sustain consistency. 

Btw. Great project. Let me know if I can further assist.

### CODE REVIEW

**Comment by sh-dv** [comment]
Thank you for the PR! I like your project as well.

However, Creating a separate route for the locale is not the best practice for this app, because it continuously communicates with the service worker. For example if I lunch the app with this PR change and switch to the french locale I will have an error and i won't be able to reach the service worker. (`http://localhost:3000/fr/service-worker.js` instead of `http://localhost:3000/service-worker.js`), and the `/file` route.

In addition, I try always to not have too much packages if I am able to do this feature manually, so installing a package for the translation is something that I thought about and decided not to.



> * Language will be chosen based on browser settings

That is already [implemented](https://github.com/sh-dv/hat.sh/blob/master/locales/index.js#L8), however I consider also writing a code where it also redirect 2 letter codes to already available similar translation. For example en-UK to en. ( I think browsers already manage that smartly, needs research).



> * If language is switched manually, it will be stored in cookie

Locale storage makes more sense because it's client-side only and more flexible in our scenario.

<br> 

And the most important thing is that you cannot use `next export` with i18n. see [here](https://nextjs.org/docs/advanced-features/i18n-routing#how-does-this-work-with-static-generation). And building this PR using `npm run build` throws this error `Error: i18n support is not compatible with next export.`

Regards
sh-dv

**Comment by stophecom** [comment]
Ahh I wasn't thinking too hard about it actually. Now I see the obstacles. 

I think having the routes translated would still be great, also for SEO. But you are right, one needed another approach for real static pages (via `next export`). This [repo](https://github.com/Xairoo/nextjs-i18n-static-page-starter) might have some pieces of the puzzle - but it would mean some more work. In any case, the present PR wouldn't help much - so I'll close it.

**Comment by sh-dv** [comment]
No worries! I will open this PR if something new comes up.

I really like some design element in scrt.link that makes it so attractive, I definitely will take some inspiration from that.

In the meanwhile, would you be interested to add a German translation for the UI? That would be really great and helpful!

**Comment by stophecom** [comment]
Here you go https://github.com/sh-dv/hat.sh/pull/51

Yeah, just let me know if you need something design related. :)

**Pull request closed without merging**
